name: CI - Test bn Utility

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run Tests
      run: ./test_script > test_results.txt

    - name: Upload Test Results
      if: ${{ always() }}

      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./test_results.txt
